exclude: "(.*/)?secrets(.yaml|/.*)"
repos:
  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--profile=black"

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        description: Autoformat shell scripts with shellcheck
        entry: ./shellcheck-fix
        language: system
        types: [shell]
        require_serial: true # shellcheck can detect sourcing this way

  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: tflint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: requirements-txt-fixer
