#!/bin/sh
# build conda but not with mounted volume as work dir
# which is crazy slow on mac
set -x

rsync -aru /io/conda-bld/ /opt/conda/conda-bld/
conda mambabuild -m /opt/conda/conda_build_config.yaml "$@"
rsync -aru /opt/conda/conda-bld/ /io/conda-bld/
