apiVersion: v1
description: "jupyterhub deployment for simula summer school"
version: 0.0.0
name: jupyterhub-simula
dependencies:
  # Ingress-Nginx to route network traffic according to Ingress resources using
  # this controller from within k8s.
  # Source code:   https://github.com/kubernetes/ingress-nginx/tree/HEAD/charts/ingress-nginx
  # App changelog: https://github.com/kubernetes/ingress-nginx/blob/HEAD/Changelog.md
  # - name: ingress-nginx
  #   version: 4.10.0
  #   repository: https://kubernetes.github.io/ingress-nginx

  # Prometheus for collection of metrics.
  # Source code:   https://github.com/prometheus-community/helm-charts/tree/HEAD/charts/prometheus
  # App changelog: https://github.com/prometheus/prometheus/blob/HEAD/CHANGELOG.md
  - name: prometheus
    version: 27.12.1
    repository: https://prometheus-community.github.io/helm-charts

  # Grafana for dashboarding of metrics.
  # Source code:   https://github.com/grafana/helm-charts/tree/HEAD/charts/grafana
  # App changelog: https://github.com/grafana/grafana/blob/HEAD/CHANGELOG.md
  - name: grafana
    version: 9.0.0
    repository: https://grafana.github.io/helm-charts

  - name: jupyterhub
    version: 4.2.0
    repository: https://jupyterhub.github.io/helm-chart
