channels:
  - conda-forge
dependencies:
  # basics, since this is starting from micromamba
  - mamba
  - conda

  # scientific packages
  - cardiac-mps
  - mps-motion
  - py-opencv

  # Nick
  - pandas
  - scikit-learn
  - pathlib

  # Andy
  - statsmodels
  - scikit-posthocs
  - scipy
  - seaborn

  # basic Python
  - python=3.10
  - black
  - isort
  - pip
  - pytest

  # IPython/Jupyter
  - jupyterlab
  - jupyterhub-base=4.0.0
  - jupyterlab_code_formatter
  - jupyterlab-git
  - jupyter-resource-usage
  - nbclassic
  - nbdime
  - notebook
  - ipykernel
  - ipywidgets
  - nbgitpuller

  # Progress-bars
  - tqdm
