channels:
  - conda-forge
  - minrk
dependencies:
  # basics, since this is starting from micromamba
  - mamba
  - conda

  # scientific packages
  - fenics-dolfinx=0.9.0
  # need 2019.2.0.dev to use ufl_legacy
  # to avoid conflict with dolfinx
  - conda-forge/label/fenics-dev::fenics=2019.2.0.dev20240219
  # - mshr=2019.1.0
  - sympy<1.14
  - neuron
  # lfpy/pytorch seem to have conflicts
  # - lfpy=2.2.5
  - lfpy
  - python-neo
  - browndye
  - brian2

  # packaged in this repo:
  - "minrk::opencarp=18"
  - "minrk::carputils=18"

  # basic Python
  - python=3.12
  - pip
  - black
  - isort
  - ruff
  - matplotlib-base
  - cython
  - scipy
  - seaborn
  - numba
  - numpy
  - pandas
  - altair
  - scikit-learn
  - pytorch-cpu
  - pytest
  - wurlitzer

  # IPython/Jupyter
  - jupyterlab=4.*
  - jupyter-resource-usage
  - jupyterhub-base=5.3.0
  - jupyterlab_code_formatter
  - jupyterlab-git
  - nbdime
  - notebook
  - ipykernel
  - ipywidgets
  - nbgitpuller

  # Progress-bars
  - tqdm
