channels:
  - conda-forge
dependencies:
  # basics, since this is starting from micromamba
  - mamba
  - conda

  # scientific packages
  - py-opencv
  - cardiac-mps
  - mps-motion
  - py-opencv

  # basic Python
  - python=3.10
  - black
  - isort

  # IPython/Jupyter
  - jupyterlab
  - jupyterhub-base=4.0.0
  - jupyterlab_code_formatter
  - jupyterlab-git
  - nbclassic
  - nbdime
  - notebook
  - ipykernel
  - ipywidgets
  - nbgitpuller

  # Progress-bars
  - tqdm
